// <auto-generated />
using System;
using GymManagement.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagement.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagement.BusinessCore.Models.ExerciseType", b =>
                {
                    b.Property<byte>("ExerciseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("ExerciseTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("ExerciseTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExerciseTypeId");

                    b.ToTable("tbExerciseTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ExerciseTypeId = (byte)1,
                            Name = "تمارين الصدر"
                        },
                        new
                        {
                            ExerciseTypeId = (byte)2,
                            Name = "تمارين البطن"
                        },
                        new
                        {
                            ExerciseTypeId = (byte)3,
                            Name = "تمارين الذراعين"
                        },
                        new
                        {
                            ExerciseTypeId = (byte)4,
                            Name = "تمارين الأرجل"
                        });
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.Period", b =>
                {
                    b.Property<byte>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("PeriodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("PeriodId"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("PeriodId");

                    b.ToTable("tbPeriods", (string)null);

                    b.HasData(
                        new
                        {
                            PeriodId = (byte)1,
                            EndTime = new TimeSpan(0, 9, 0, 0, 0),
                            PeriodName = "الصباحية",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PeriodId = (byte)2,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            PeriodName = "الصباحية المتأخرة",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            PeriodId = (byte)3,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            PeriodName = "الظهيرة",
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            PeriodId = (byte)4,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            PeriodName = "المسائية",
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            PeriodId = (byte)5,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            PeriodName = "الليلية",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("NationalNumber");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("RegisterationDate")
                        .HasColumnType("date");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThirdName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UniqueEmail")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex(new[] { "NationalNumber" }, "UniqueNationalNumber")
                        .IsUnique()
                        .HasFilter("[NationalNumber] IS NOT NULL");

                    b.HasIndex(new[] { "PhoneNumber" }, "UniquePhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("tbPerson", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("int")
                        .HasColumnName("CoachID");

                    b.Property<int?>("CreatedByReceptionistId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByReceptionistID");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte>("ExcerciseTypeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("ExcerciseTypeID");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<byte>("PeriodId")
                        .HasColumnType("tinyint")
                        .HasColumnName("PeriodID");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte>("SubscriptionPeriodId")
                        .HasColumnType("tinyint")
                        .HasColumnName("SubscriptionPeriodID");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("ExcerciseTypeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("SubscriptionPeriodId");

                    b.ToTable("tbSubscriptions", (string)null);
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.SubscriptionPeriod", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("PeriodDays")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("smallmoney");

                    b.HasKey("Id");

                    b.ToTable("tbSubsciptionPeriods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "يومي",
                            PeriodDays = (byte)1,
                            Price = 1000.00m
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "أسبوعي",
                            PeriodDays = (byte)7,
                            Price = 5000.00m
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "شهري",
                            PeriodDays = (byte)30,
                            Price = 15000.00m
                        });
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.Member", b =>
                {
                    b.HasBaseType("GymManagement.BusinessCore.Models.Person");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("MemberWeight")
                        .HasColumnType("decimal(5, 2)");

                    b.ToTable("tbMembers", (string)null);
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.Subscription", b =>
                {
                    b.HasOne("GymManagement.BusinessCore.Models.ExerciseType", "ExcerciseType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ExcerciseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbExerciseType");

                    b.HasOne("GymManagement.BusinessCore.Models.Member", "Member")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbMember");

                    b.HasOne("GymManagement.BusinessCore.Models.Period", "Period")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbPeriod");

                    b.HasOne("GymManagement.BusinessCore.Models.SubscriptionPeriod", "SubscriptionPeriod")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriptionPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbSubscriptionPeriod");

                    b.Navigation("ExcerciseType");

                    b.Navigation("Member");

                    b.Navigation("Period");

                    b.Navigation("SubscriptionPeriod");
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.Member", b =>
                {
                    b.HasOne("GymManagement.BusinessCore.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("GymManagement.BusinessCore.Models.Member", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.ExerciseType", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.Period", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.SubscriptionPeriod", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("GymManagement.BusinessCore.Models.Member", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
