// <auto-generated />
using System;
using Jym_Management_DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jym_Management_DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbEmployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    b.Property<DateTime>("ResignationDate")
                        .HasColumnType("date")
                        .HasColumnName("resignationDate");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.HasKey("EmployeeId")
                        .HasName("PK_tbk");

                    b.HasIndex("PersonId");

                    b.ToTable("tbEmployees", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbExerciseType", b =>
                {
                    b.Property<byte>("ExerciseTypeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("ExerciseTypeID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExerciseTypeId");

                    b.ToTable("tbExerciseTypes", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbJob", b =>
                {
                    b.Property<byte>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("JobID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("JobId"), 1L, 1);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("jobTitle");

                    b.HasKey("JobId");

                    b.ToTable("tbJobs", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbJobHistory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("EmpoyeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmpoyeeID");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte>("JobId")
                        .HasColumnType("tinyint")
                        .HasColumnName("JobID");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("tbJobHistories", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"), 1L, 1);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<decimal?>("MemberWeight")
                        .HasColumnType("decimal(2,2)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    b.HasKey("MemberId");

                    b.HasIndex("PersonId");

                    b.ToTable("tbMembers", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPayrollPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("paymentID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("paymentDate");

                    b.HasKey("PaymentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("tbPayroll_payments", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPeriod", b =>
                {
                    b.Property<byte>("PeriodId")
                        .HasColumnType("tinyint")
                        .HasColumnName("PeriodID");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("PeriodId");

                    b.ToTable("tbPeriods", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPermssion", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<byte?>("RoleId")
                        .HasColumnType("tinyint")
                        .HasColumnName("RoleID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("tbPermssions", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Idcard")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("IDCard");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PersonId");

                    b.HasIndex(new[] { "PhoneNumber" }, "UniquePhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("tbPerson", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbRole", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("tbRoles", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbSubsciptionPeriod", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("smallmoney");

                    b.HasKey("Id");

                    b.ToTable("tbSubsciptionPeriods", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionID");

                    b.Property<int>("CoachId")
                        .HasColumnType("int")
                        .HasColumnName("CoachID");

                    b.Property<int>("CreatedByReceptionistId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByReceptionistID");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte>("ExcerciseTypeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("ExcerciseTypeID");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<byte>("PeriodId")
                        .HasColumnType("tinyint")
                        .HasColumnName("PeriodID");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte>("SubscriptionPeriodId")
                        .HasColumnType("tinyint")
                        .HasColumnName("SubscriptionPeriodID");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("CoachId");

                    b.HasIndex("CreatedByReceptionistId");

                    b.HasIndex("ExcerciseTypeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("SubscriptionPeriodId");

                    b.ToTable("tbSubscriptions", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbSubscriptionPayment", b =>
                {
                    b.Property<short?>("CreatedByUserId")
                        .HasColumnType("smallint")
                        .HasColumnName("CreatedByUserID");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("smallmoney");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("SubscriptionID");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("tbSubscriptionPayments", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbUser", b =>
                {
                    b.Property<short>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("UserId"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("PermissionsId")
                        .HasColumnType("tinyint")
                        .HasColumnName("permissionsID");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("PermissionsId");

                    b.HasIndex("PersonId");

                    b.HasIndex(new[] { "UserName" }, "UniqueUserName")
                        .IsUnique();

                    b.ToTable("tbUsers", (string)null);
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbEmployee", b =>
                {
                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbPerson", "Person")
                        .WithMany("TbEmployees")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbJobHistory", b =>
                {
                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbJob", "Job")
                        .WithMany("TbJobHistories")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_tbJobHistories_tbJobs");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbMember", b =>
                {
                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbPerson", "Person")
                        .WithMany("TbMembers")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Members");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPayrollPayment", b =>
                {
                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbEmployee", "Employee")
                        .WithMany("TbPayrollPayments")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Payroll_payments");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPermssion", b =>
                {
                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbRole", "Role")
                        .WithMany("TbPermssions")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_permissions");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbSubscription", b =>
                {
                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbJobHistory", "Coach")
                        .WithMany("TbSubscriptionCoaches")
                        .HasForeignKey("CoachId")
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbJobHistories_Coach");

                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbJobHistory", "CreatedByReceptionist")
                        .WithMany("TbSubscriptionCreatedByReceptionists")
                        .HasForeignKey("CreatedByReceptionistId")
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbJobHistoriesRecep");

                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbExerciseType", "ExcerciseType")
                        .WithMany("TbSubscriptions")
                        .HasForeignKey("ExcerciseTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbExerciseType");

                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbMember", "Member")
                        .WithMany("TbSubscriptions")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbMember");

                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbPeriod", "Period")
                        .WithMany("TbSubscriptions")
                        .HasForeignKey("PeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbPeriod");

                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbSubsciptionPeriod", "SubscriptionPeriod")
                        .WithMany("TbSubscriptions")
                        .HasForeignKey("SubscriptionPeriodId")
                        .IsRequired()
                        .HasConstraintName("FK_tbSubscriptions_tbSubscriptionPeriod");

                    b.Navigation("Coach");

                    b.Navigation("CreatedByReceptionist");

                    b.Navigation("ExcerciseType");

                    b.Navigation("Member");

                    b.Navigation("Period");

                    b.Navigation("SubscriptionPeriod");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbSubscriptionPayment", b =>
                {
                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_tbSubscriptionPayments_tbUsers");

                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbSubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .HasConstraintName("FK_tbSubscriptionPayments_tbSubscriptions");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbUser", b =>
                {
                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbPermssion", "Permissions")
                        .WithMany("TbUsers")
                        .HasForeignKey("PermissionsId")
                        .IsRequired()
                        .HasConstraintName("FK_tbUsers");

                    b.HasOne("Jym_Management_DataAccessLayer.Entities.TbPerson", "Person")
                        .WithMany("TbUsers")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_tbUsers_tbPerson");

                    b.Navigation("Permissions");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbEmployee", b =>
                {
                    b.Navigation("TbPayrollPayments");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbExerciseType", b =>
                {
                    b.Navigation("TbSubscriptions");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbJob", b =>
                {
                    b.Navigation("TbJobHistories");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbJobHistory", b =>
                {
                    b.Navigation("TbSubscriptionCoaches");

                    b.Navigation("TbSubscriptionCreatedByReceptionists");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbMember", b =>
                {
                    b.Navigation("TbSubscriptions");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPeriod", b =>
                {
                    b.Navigation("TbSubscriptions");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPermssion", b =>
                {
                    b.Navigation("TbUsers");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbPerson", b =>
                {
                    b.Navigation("TbEmployees");

                    b.Navigation("TbMembers");

                    b.Navigation("TbUsers");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbRole", b =>
                {
                    b.Navigation("TbPermssions");
                });

            modelBuilder.Entity("Jym_Management_DataAccessLayer.Entities.TbSubsciptionPeriod", b =>
                {
                    b.Navigation("TbSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
